### ISSUE TITLE
URL encoding of AppID parameter for Chamberlain and Liftmaster is broken

### ISSUE THREAD

**Issue by angelosk** [FlyingDiver/Indigo-MyQ#1]
For both appIDs, you should replace the "%2f" character near the end of the hard-coded strings at the top of plugin.py with '/' (slash) --- Python's requests module sees the '%' and URL encodes it by itself, giving:

j8pQggXLhLy0WHahglCD4N1nAkkXQtGYpq2HrHD7H1nvmbT55KqtN6RSF4ILB%252fi

(Note the "%25" near the end)

**Comment by FlyingDiver** [comment]
Fixed in v0.0.12
