### ISSUE TITLE
getDevices failure, status_code = 400

### ISSUE THREAD

**Issue by janngobble** [FlyingDiver/Indigo-MyQ#15]
Started plugin "MyQ 7.5.3"
   MyQ                             Starting MyQ
   MyQ Warning                     getDevices failure, status_code = 400

What else do you need me to include? I would've included the dump but I don't know if the Account/userid is private to me so i did not.

**Comment by FlyingDiver** [comment]
See https://forums.indigodomo.com/viewtopic.php?f=214&t=24829

**Comment by janngobble** [comment]
This worked for me! Thanks!!!
