### ISSUE TITLE
Version 7.7.2 - Initially works then stops

### ISSUE THREAD

**Issue by farberm** [FlyingDiver/Indigo-MyQ#23]
FlyingDriver:
Thanks for a great plugin. 

I have upgraded to the 7.7.2 pre-release and installed all the python requirements. When I enable the plugin it works for a short time without any issue. After a bit of time however, it stop responding. (The MyQ app on my iphone still works)

This seems to occur exactly 10 min after I reload the pugin.

Send pymyq message: {"cmd": "update"}
   MyQ Debug                       Received pymyq message: {"msg": "echo", "request": {"cmd": "update"}}
   MyQ Debug                       Received pymyq message: 
   MyQ Warning                     Zero length message from subprocess
   MyQ Debug                       Received pymyq message: 
   MyQ Warning                     Zero length message from subprocess
   MyQ Debug                       Send pymyq message: {"cmd": "accounts"}
   MyQ Warning                     IOError writing to subprocess: '[Errno 32] Broken pipe'

 I have turned on debugging and the only issue is a Warning error "Zero length message from subprocess" and an occasional warning of a "Broken Pipe" Any ideas what could be going on. I am on BigSur 11.6 and Indigo 2021.1.2

**Comment by FlyingDiver** [comment]
At this point, the only solution is to restart the plugin.  The problem is that the Python3 process has stopped for some unknown reason.  It's on my list to attempt to restart the sub-process when the error is detected, but I haven't done it yet.

**Comment by farberm** [comment]
Thx for the update
