### ISSUE TITLE
warning bug

### ISSUE THREAD

**Issue by darrenl** [FlyingDiver/Indigo-MyQ#26]
After some time of normal operation, I am getting this in the logs and the plugin stops being able to control my garage door:

MyQ Warning                     Zero length message from subprocess
   MyQ Warning                     Zero length message from subprocess
   MyQ Warning                     Zero length message from subprocess
   MyQ Warning                     Zero length message from subprocess
   MyQ Warning                     Zero length message from subprocess
   MyQ Warning                     Zero length message from subprocess
   MyQ Warning                     Zero length message from subprocess
   MyQ Warning                     Zero length message from subprocess
   MyQ Warning                     Zero length message from subprocess
   MyQ Warning                     Zero length message from subprocess
   MyQ Warning                     Zero length message from subprocess
   MyQ Warning                     Zero length message from subprocess
   MyQ Warning                     Zero length message from subprocess
   MyQ Warning                     Zero length message from subprocess
   MyQ Warning                     Zero length message from subprocess
   MyQ Warning                     Zero length message from subprocess

**Comment by darrenl** [comment]
Let me know what else I can dump or do in my setup to help debug...  Thanks!

**Comment by FlyingDiver** [comment]
Not to be fixed.  That's a result of the method used to run the Python3 library under Python 2.  No updates will be made to this version of the plugin.  You'll need to wait for the pure Python3 version in Indigo 2022.1.

**Comment by darrenl** [comment]
I’m on 2022.2 with python three installed?

Cheers,
Darren

**Comment by darrenl** [comment]
Sorry I’m confused. 2021.2. Got it

Cheers,
Darren
