### ISSUE TITLE
Triggers Based on Battery Status

### ISSUE THREAD

**Issue by ukiews** [FlyingDiver/Indigo-MyQ#30]
Is there a way to create a trigger when the garage sensor indicates LOW Battery?

**Comment by FlyingDiver** [comment]
I've never seen battery status in any MyQ data.  Where do you see it?

**Comment by ukiews** [comment]
I don’t. Does the api simply not provide this information?

**Comment by FlyingDiver** [comment]
Nope.  You can see the data available from the API using the plugin menu command.
