### ISSUE TITLE
sslv3 handshake error

### ISSUE THREAD

**Issue by cjvilches** [FlyingDiver/Indigo-MyQ#8]
After upgrading to 7.3.2 I get the following error after restarting the plugin.
myqLogin failure, RequestException: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:590).

I suspect a py version incompatibility.  Thanks for looking into it.

**Comment by FlyingDiver** [comment]
What version were you on before, and what versions of Indigo and MacOS are you running?

**Comment by cjvilches** [comment]
Hi Joe, running MacOS10.11.6 and indigo 7.3.  Was running plugin 7.3.1.  Thanks.

**Comment by FlyingDiver** [comment]
Your problem is MacOS 10.11.  It doesn't support the version of Python SSL that's now needed for MyQ.  The fact that it stopped working after upgrading to 7.3.2 is a coincidence.

Check the forums, there's several threads about this dating back six months or so.

**Comment by FlyingDiver** [comment]
You need High Sierra (10.13) or Mojave (10.14).

**Comment by cjvilches** [comment]
Thanks for the prompt response.  Had stayed at 10.11 to minimize risks with indigo 6.x.   

Will upgrade to 10.14 now that I have indigo 7.

CarlosV
